### ISSUE TITLE
ORIGINAL EXCEPTION: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by dharveshmydeen** [solodynamo/ng2-search-filter#1]
it is not working in mdDialog box

**Comment by solodynamo** [comment]
Can you share snippet where you have imported the module as filter undefined error comes when you have either wrongly imported the module or have not imported.

**Comment by solodynamo** [comment]
I think your issue got resolved so i am closing this issue for now but you can reopen in future if required.
