### ISSUE TITLE
How to reset filter state?

### ISSUE THREAD

**Issue by studenttsu** [solodynamo/ng2-search-filter#10]

**Comment by studenttsu** [comment]
For example, I need to reset state filter after closing search form.

**Comment by solodynamo** [comment]
Hey , can be little more descriptive about what are you trying to achieve .

**Comment by aVolpe** [comment]
Hi @studenttsu I add an example to show you how to clear the filter state, check this [commit](https://github.com/aVolpe/ng2-search-filter-example-project/commit/ee55b5f6961e771321ab3e0a554c9b9bd52d31ec).

Basically you need to set the filter value to `''`.
