### ISSUE TITLE
Skips First letter of the  

### ISSUE THREAD

**Issue by rehamayman96** [solodynamo/ng2-search-filter#11]
i tried to use it but it skips the first letter as a pass an array of objects not only strings

**Comment by solodynamo** [comment]
Hi,
 can you please share a snippet on what you trying to do ? It will help everyone.

**Comment by M1kemay** [comment]
I have a similar issue, typing any single character in the input field will show up the entire list even if the char is unmatched, i.e. "z" (when no field has a z in it). haven't tested whether it skips that char though, as in matches `abcd` instead of `zabcd`. If there's any code i can provide that will help, let me know.

**Comment by solodynamo** [comment]
Would love to accept a PR for this.

**Comment by Abdul993** [comment]
Hi,
Even I am facing the same issue of passing array of objects to search but the list remains still, and begins search from 2nd letter, Thank you.

**Comment by aVolpe** [comment]
@Abdul993 can you provide with the relevant part of your code? 

Can you check that your input is updating every keystroke?

You can try putting `{{ searchTerm }}` bellow your input to see if Angular is updating the value with every keystroke?

**Comment by rehamayman96** [comment]
i know it is late put i have solved the problem, 
1- this filter fine only if the object is a string 
2- if you pass an object of ; for example { name: "Anna", gender:"female"}, it will search in all attributes not only the name (if you want to filter by name)
The Solution is that : 
u need to modify the module passed on the attribute you need to search for  , or implement the filter your self.
Here is a screenshot to my code where my attribute that i filter on is -> name_en 

![capture](https://user-images.githubusercontent.com/25254134/38455862-1f70b662-3a7e-11e8-93f7-b70db0cdb3e9.PNG)

**Comment by aVolpe** [comment]
Yes!, one of the features of this library is the ability to make a "deep search" of the properties of the object.

We will try to provide a way to make the search customizable.
