### ISSUE TITLE
Angular 2 search issue.

### ISSUE THREAD

**Issue by gaurav64941** [solodynamo/ng2-search-filter#19]
__webpack_require__.i(...) is not a function

**Comment by solodynamo** [comment]
Hi,
Please elaborate on the issue, at first glance not seems  an `ng2-search-filter` related issue.

**Comment by solodynamo** [comment]
`webpack_require.i(...)` is not a function  usually comes when you are using webpack and have imported a module from some `../../x` location but that module does not exist in `x` location.
