### ISSUE TITLE
it should provide a event for returning filter data

### ISSUE THREAD

**Issue by lzm420241** [solodynamo/ng2-search-filter#2]

**Comment by solodynamo** [comment]
It already returns the data automatically on keyup event and shows them as  suggestions .

**Comment by lzm420241** [comment]
so,how can i get filter data from origin data if i press a key?

**Comment by solodynamo** [comment]
If you see the gif , this filter automatically returns the matched elements in the dropdown. Btw what you actually trying to do??

**Comment by solodynamo** [comment]
Closing this issue for now, you may open in future if required.
