### ISSUE TITLE
Upgrade to angular 5

### ISSUE THREAD

**Issue by dfront** [solodynamo/ng2-search-filter#22]
Hi, i get this error when update myproject to angular5
**ng build --env=homolog -

Module build failed: Error: /var/www/html/.../node_modules/ng2-search-filter/src/ng2-filter.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/var/www/html/..../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:653:23)
    at plugin.done.then (/var/www/html/...../node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/app.module.ngfactory.js 80:0-63
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./node_modules/ng2-search-filter/src/ng2-filter.pipe.ts
Module build failed: Error: /var/www/html/...../node_modules/ng2-search-filter/src/ng2-filter.pipe.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file se& ng build --env=homolog --prod  --aot ems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/var/www/html/..../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:653:23)
    at plugin.done.then (/var/www/html/....node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/dashboard/robot-instance/robot-instance.component.ngfactory.js 32:0-61
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts

**Comment by solodynamo** [comment]
Hey @dfront ,
I didn't checked the package with angular 5 release and as it seems , its breaking . I have been lil busy lately and i will be more than happy to accept a PR supporting the angular 5 version.

**Comment by aVolpe** [comment]
I am using this filter in a angular 5 ionic 3 application, this library works fine.

The document that specify the new format of the libraries is [this](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview)

I thinks we can create a new branch and work there to adapt the pacakge to the new format.

**Comment by solodynamo** [comment]
@aVolpe sounds nice to make the package adaptable to new format in a separate branch. You may follow up on this issue and make a PR as this might occur with other devs using this package.

**Comment by pedro412** [comment]
Hi, has anyone fix this?

or know something?

----------------------------------

ERROR in ./node_modules/ng2-search-filter/index.ts
Module build failed: Error: C:\Users\Pedro\Desktop\ngsignoss\signossApp\node_modules\ng2-search-filter\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Pedro\Desktop\ngsignoss\signossApp\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:656:23)
    at plugin.done.then (C:\Users\Pedro\Desktop\ngsignoss\signossApp\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./src/app/app.module.ts 22:26-54
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by aVolpe** [comment]
@pedro412 what version of ng2-search-filter are you using? that file doesn't exists, how are you importing the module? can you please show us your module.ts?

**Comment by pedro412** [comment]
Hi Sure, ng2-search-filter@0.4.1:

when installing it gives me this WARNS: 
-----------------------------------------
![err1](https://user-images.githubusercontent.com/24465570/36164852-4629d54e-10b3-11e8-86eb-b145f0d3455a.png)

-----------------------------------------


Then when trying to import:
---------------------------------
![err2](https://user-images.githubusercontent.com/24465570/36165131-2454a56a-10b4-11e8-8af0-301f643d2cb1.png)

---------------------------------



and finally it gives me the error ❌ 
--------------------------------------


ERROR in ./node_modules/ng2-search-filter/index.ts
Module build failed: Error: C:\Users\admpalvarez\Desktop\chile\v1\FarmaciasChile\node_modules\ng2-search-filter\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\admpalvarez\Desktop\chile\v1\FarmaciasChile\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:656:23)
    at plugin.done.then (C:\Users\admpalvarez\Desktop\chile\v1\FarmaciasChile\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
 @ ./src/app/pages/pages.module.ts 23:26-54
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by aVolpe** [comment]
@solodynamo I thinks this issue is with the `postinstall` script, this is not longer neccesary with the new package format, check #32
