### ISSUE TITLE
Compilation error with Angular 5 and webpack

### ISSUE THREAD

**Issue by chrizzle** [solodynamo/ng2-search-filter#24]
Hi,
I'm experiencing the following compilation error on Angular 5 and webpack:

[0]
[0]
[0] ERROR in [at-loader] ./node_modules/ng2-search-filter/src/ng2-filter.pipe.ts:17:34
[0]     TS7006: Parameter 'item' implicitly has an 'any' type.
[0] webpack: Failed to compile.

Any idea on how to fix this?

Cheers,
Christopher

**Comment by aVolpe** [comment]
You are using the falg `--noImplicitAny` for compiling your `ts`, I will create a pull request to fix this issue.

**Comment by chrizzle** [comment]
Ah yes, that did it! Thanks for the super quick response, still learning the ropes here.

Best regards,
Christopher
