### ISSUE TITLE
Unexpected value 'undefined' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by Sanafan** [solodynamo/ng2-search-filter#28]
For using the `| filter:term` pipe i installed the [ng2-search-filter][1] module. VisualStudio already underlined `filter` red and tells me, that `the pipe 'filter' is unknown`.

My app doesn't compile, when i include the Ng2SearchPipeModule which i did like 

`import { Ng2SearchPipeModule } from 'ng2-search-filter';` and of course i also imported it inside my imports as `Ng2SearchPipeModule`. After doing so, Console says `Unexpected value 'undefined' imported by the module 'AppModule'`.

So this is my app.module.ts:

    import { BrowserModule } from '@angular/platform-browser';
    import { NgModule } from '@angular/core';
    import { FormsModule, ReactiveFormsModule } from '@angular/forms';
    import { HttpModule } from '@angular/http';
    import { RouterModule, Routes } from '@angular/router';
    import { FlashMessagesModule } from 'angular2-flash-messages/module';
    import { MatFormFieldModule, MatAutocompleteModule, MatInputModule } from '@angular/material';
    import { MatCheckboxModule } from '@angular/material/checkbox';
    import { MatRadioModule } from '@angular/material/radio';
    import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
    import { AgmCoreModule } from '@agm/core';
    import { Ng2SearchPipeModule } from 'ng2-search-filter';
    
    import { AuthGuard } from './guards/auth.guard';
    import { AdminGuard } from './guards/admin.guard';
    
    import { AuthService } from './services/auth.service';
    import { TerminalService } from './services/terminal.service';
    import { ValidateService } from './services/validate.service';
    import { CustomerService } from './services/customer.service';
    import { GeolocationService } from './services/geolocation.service';
    import { StockService } from './services/stock.service';
    
    import { AppComponent } from './app.component';
    import { NavbarComponent } from './components/navbar/navbar.component';
    import { LoginComponent } from './components/login/login.component';
    import { RegisterComponent } from './components/register/register.component';
    
    const appRoutes: Routes = [
      {path: '', component: HomeComponent},
      {path: 'register', component: RegisterComponent},
      {path: 'login', component: LoginComponent},
      {path: 'dashboard', component: DashboardComponent, canActivate: [AuthGuard]},
      {path: 'profile', component: ProfileComponent, canActivate: [AuthGuard]},
      {path: 'createTerminal', component: TerminalsCreateComponent, canActivate: [AuthGuard]},
      {path: 'search', component: TerminalsSearchComponent, canActivate: [AuthGuard]},
      {path: 'admin', component: AdminComponent, canActivate: [AdminGuard]},
      {path: 'admin/createTerminalTypes', component: AdminComponent, canActivate: [AdminGuard]},
      {path: 'admin/customer', component: AdminComponent, canActivate: [AdminGuard]}
    ];
    
    @NgModule({
      declarations: [
        AppComponent,
        NavbarComponent,
        LoginComponent,
        RegisterComponent
      ],
      imports: [
        BrowserModule,
        FormsModule,
        ReactiveFormsModule,
        HttpModule,
        RouterModule.forRoot(appRoutes),
        FlashMessagesModule.forRoot(),
        MatFormFieldModule,
        MatAutocompleteModule,
        MatInputModule,
        MatCheckboxModule,
        BrowserAnimationsModule,
        MatRadioModule,
        AgmCoreModule.forRoot({apiKey: 'xxxxxxxxxxxxxxxxxxxx'}),
        Ng2SearchPipeModule
      ],
      providers: [ValidateService, AuthService, AuthGuard, AdminGuard, TerminalService, CustomerService, GeolocationService, StockService],
      bootstrap: [AppComponent]
    })
    export class AppModule { }

  [1]: https://github.com/solodynamo/ng2-search-filter

**Comment by aVolpe** [comment]
Hi, can you send the log of your build?

I make a pull request #29 that fix a related issue!

**Comment by solodynamo** [comment]
@Sanafan The PR by @aVolpe was merged and hopefully your issue was solved. You may re-open this if encounter same issue in future.
