### ISSUE TITLE
Post Installation Error

### ISSUE THREAD

**Issue by madhurakhal** [solodynamo/ng2-search-filter#3]
![screen shot 2017-03-06 at 4 01 33 pm](https://cloud.githubusercontent.com/assets/839882/23615321/50ff89e6-0286-11e7-95eb-efdb48005730.png)

**Comment by solodynamo** [comment]
Hii madhurakhal, seems like you dont have typings install as global dependency  so run this command npm install typings -g . It would work .

**Comment by solodynamo** [comment]
Closing this issue for now.If still getting the problem you can open again.

**Comment by danilorb** [comment]
@solodynamo Thank you. The command 'npm install typings -g' solved my problem.
