### ISSUE TITLE
Index after filtering

### ISSUE THREAD

**Issue by VoroshilovMax** [solodynamo/ng2-search-filter#34]
I have code =
` <tr *ngFor="let row of data | filter: filter | orderBy: key : reverse | paginate: { itemsPerPage: perPage, currentPage: page } ; let i = index ;"`

and I want to use splice() method for delete one row from table, but after filtering index work not correct... I can`t delete chosen row...
How I can fix this issue?

**Comment by VoroshilovMax** [comment]
I found solution. Instead 

```
  deleteRow(index){
    this.data.splice(index, 1);
}
```

should to use method splice() with indexOf()

```
  deleteRow(row){
   let index = this.data.indexOf(row);
    this.data.splice(index, 1);
}
```

**Comment by aVolpe** [comment]
Yes, your problem is that the index of your "data" it's not the same of the "*ngFor", because the filter plugin altered the order, your second solution should work fine.
