### ISSUE TITLE
ng identifier "term" is not defined in template

### ISSUE THREAD

**Issue by DiMilan** [solodynamo/ng2-search-filter#37]
I followed all the steps from the readme.
1. install
2. imported in app.module
3. and added it to my component template

```
 <input type="text" class="form-control" placeholder="Filter on name" [(ngModel)]="term">
 <ul *ngFor="let team of teams | filter: term" class="collection">
```

term is underlined for both instances. App compiles and runs, nothing gets filtered. Angular version 5

**Comment by aVolpe** [comment]
Can you try one of these:

1. Add term as a property in your controller
2. Add `{{ term }}` below the input to check if it's updated

**Comment by arcsector** [comment]
@DiMilan in your `component.ts`, add the following to the exported component class:
```typescript
term = '';
```
So that your exported class looks like:
```typescript
// imports up here
export class MyComponent implements OnInit {
  term = '';
  // rest of my content
}
```
