### ISSUE TITLE
build getting error: ERROR in Ng2SearchPipeModule is not an NgModule

### ISSUE THREAD

**Issue by eduzera** [solodynamo/ng2-search-filter#4]
Hi,

I added the `ng2-search-filter` to my project. But on building process i getting this message:

```
ERROR in Ng2SearchPipeModule is not an NgModule
```

node version: __v6.9.5__
angular CLI: __1.0.0-beta.31__

Some example how i used:

```js
import { Ng2SearchPipeModule } from 'ng2-search-filter';

@NgModule({
  imports: [
    ...,
    Ng2SearchPipeModule
  ],
  ...
```

Someone got this error before?

Thanks

**Comment by solodynamo** [comment]
Hey ,
No one experienced this issue ,But there are some issues with angular-cli and this thread might help you https://github.com/angular/angular-cli/issues/3426 . Hope this helps.

**Comment by eduzera** [comment]
Ok, i can't solve the problem.

I didn't have enough time, so i imported the pipe code to my project and it's worked.

It's not the right way, but i needed to to that.

Thanks @solodynamo for your attention.

**Comment by kalew8** [comment]
I'm experiencing the same issue with the latest update.

**Comment by wickedrahul** [comment]
me too

**Comment by solodynamo** [comment]
This issue has been fixed in latest release i.e version: 0.3.1.

**Comment by subhranshu00** [comment]
Just run the ng serve command in terminal window, the error will not appear again.

**Comment by hariomjee** [comment]
> 
amazing...really this works in my system.
