### ISSUE TITLE
Ng2 search is not searching for letter d and g correctly 

### ISSUE THREAD

**Issue by sunilpatra27** [solodynamo/ng2-search-filter#42]
While i searched for letter "d" no change in the list and while searched for "g" it is shows result for G and X

**Comment by solodynamo** [comment]
Hi,
Searching largely depends on the data on which it is applied. Pls give examples of data you are feeding to the filter so that me or @aVolpe can look further in it.

**Comment by sunilpatra27** [comment]
Hii @solodynamo and  @aVolpe thanks for response 
,My array is like this ["Nokia","Honor","Doctabse","game","book","xiomi"];
while  searching for "g" i am getting filter view for both "xiomi" and "game" 
while searching  for "d" is not giving any thing

**Comment by aVolpe** [comment]
@sunilpatra27 I can't reproduce your issue, can you provide more code?

This is my code:

```ts
issue42data =  ["Nokia","Honor","Doctabse","game","book","xiomi"];
issue42input = '';
```


```html
<h2>Issue 42</h2>
    <input type="text" [(ngModel)]="issue42input" />
    <div *ngFor="let item of issue42data | filter:issue42input ">
        <p>
            {{item}}
        </p>
    </div>
```

And this code works.

**Comment by Michaelwan777** [comment]
> g

I try your case in my project which also used this plugin. It works well. Probably some errors exist other code block. Regards.

**Comment by Michaelwan777** [comment]
@sunilpatra27 
I try your case in my project which also used this plugin. It works well. Probably some errors exist another code block. Regards.

**Comment by sunilpatra27** [comment]
Hii,

Thanks all that issue is resolved. As I have some randomly generated keys
in mongo which contains the letters so it was working like that.

Thanks for your response again.
Code code and code...

**Comment by aVolpe** [comment]
Thanks for the update @sunilpatra27
