### ISSUE TITLE
Version4.9 is not working 

### ISSUE THREAD

**Issue by khairnaraksh** [solodynamo/ng2-search-filter#47]
I am using this package in my project. After updation of version 4.9 my application is crashed

**Comment by solodynamo** [comment]
What is the error you are getting? pls attach the screenshot and describe your error in brief.

**Comment by aVolpe** [comment]
@khairnaraksh we can reproduce the issue and we are working in a soluciton, in the meantime you can fix it changint the import of the module to:

```js
import { Ng2SearchPipeModule } from 'ng2-search-filter/dist/ng2-search-filter';
```

**Comment by aVolpe** [comment]
@khairnaraksh the version 0.5.1 fixes this issue, I updated the stackblitz (https://stackblitz.com/edit/issue47) so you can see it in action!.

**Comment by khairnaraksh** [comment]
yes Thanx... Happy Coding...
