### ISSUE TITLE
<ng2-search-filter not providing correct search values>

### ISSUE THREAD

**Issue by sohini-nandi-tfs** [solodynamo/ng2-search-filter#50]
**please open the following link:**

https://stackblitz.com/edit/ng2-search-filter-example?file=src%2Fapp%2Fapp.component.html

this is a very simple example of using ng2-search-filter in angular. This is the screenshot of the search screen where if we do not provide anything in the search box, all the results will be shown.

![image](https://user-images.githubusercontent.com/61404310/75755659-0d011700-5d55-11ea-8e15-ca44819647e5.png)

now I am providing 'yl' in input box, it should give Kyle as a result, but instead of that it is showing nothing.

![image](https://user-images.githubusercontent.com/61404310/75755702-22764100-5d55-11ea-9c60-f0a9b82b2d62.png)

**Comment by prashantpimpale93** [comment]
I thinks its currently not supporting to search over an array of strings (Not sure) if not then will be available soon.

For time beings, you can create your own custom pipe with below code:

```
import { Pipe, PipeTransform, Injectable } from "@angular/core";

@Pipe({
  name: "filter",
  pure: false
})
@Injectable()
export class Custom_Ng2SearchPipe implements PipeTransform {

  transform(items: any, term: string, excludes: any = []): any {
    if (!term || !items) return items;
    return Custom_Ng2SearchPipe.filter(items, term, excludes);
  }

  static filter(
    items: Array<{ [key: string]: any }>,
    term: string,
    excludes: any
  ): Array<{ [key: string]: any }> {
    const toCompare = term.toLowerCase();

    function checkInside(item: any, term: string) {
      if (
        typeof item === "string" &&
        item
          .toString()
          .toLowerCase()
          .includes(toCompare)
      ) {
        return true;
      }

      for (let property in item) {
        if (
          item[property] === null ||
          item[property] == undefined ||
          excludes.includes(property)
        ) {
          continue;
        }

        if (typeof item[property] === "object") {
          if (checkInside(item[property], term)) {
            return true;
          }
        } else if (
          item[property]
            .toString()
            .toLowerCase()
            .includes(toCompare)
        ) {
          return true;
        }
      }
      return false;
    }

    return items.filter(function (item) {
      return checkInside(item, term);
    });
  }
}
```

Here is the [working demo](https://stackblitz.com/edit/ng2-search-filter-example-boknjv) which is working for all types:)

**Comment by prashantpimpale93** [comment]
@aVolpe Have raised PR with related to this issue, please review!
