### ISSUE TITLE
does this support Angular 9?

### ISSUE THREAD

**Issue by chris19960730** [solodynamo/ng2-search-filter#55]
Hi, I wanna use this in my Angular 9 but didn't work. I wonder if this is incompatible?

**Comment by aVolpe** [comment]
Hi @chris19960730 what issue do you have? can you share your code?

**Comment by chris19960730** [comment]
Hi, when I import it in app.module.ts, my console shows 
![image](https://user-images.githubusercontent.com/18096241/78073781-63fb0b80-7356-11ea-8c8f-251383140dc7.png)
Is there any idea to fix it?

**Comment by aVolpe** [comment]
Maybe a change in the compilation proccess is required to support Ivy. In the meantime, you can include the filter by hand in your project (it's only a component).

**Comment by chris19960730** [comment]
Thanks! But I don't know how to include it myself, can you give me some instructions?

**Comment by chris19960730** [comment]
> Maybe a change in the compilation proccess is required to support Ivy. In the meantime, you can include the filter by hand in your project (it's only a component).

Hi, could you share with me how to include it I'm my project?  I have no idea... Thanks a lot

**Comment by prashantpimpale93** [comment]
@chris19960730 Create a pipe if your project and just replace it with below code:

```
import { Pipe, PipeTransform, Injectable } from "@angular/core";

@Pipe({
  name: "filter",
  pure: false
})
@Injectable()
export class Custom_Ng2SearchPipe implements PipeTransform {

  transform(items: any, term: string, excludes: any = []): any {
    if (!term || !items) return items;
    return Custom_Ng2SearchPipe.filter(items, term, excludes);
  }

  static filter(
    items: Array<{ [key: string]: any }>,
    term: string,
    excludes: any
  ): Array<{ [key: string]: any }> {
    const toCompare = term.toLowerCase();

    function checkInside(item: any, term: string) {
      if (
        typeof item === "string" &&
        item
          .toString()
          .toLowerCase()
          .includes(toCompare)
      ) {
        return true;
      }

      for (let property in item) {
        if (
          item[property] === null ||
          item[property] == undefined ||
          excludes.includes(property)
        ) {
          continue;
        }

        if (typeof item[property] === "object") {
          if (checkInside(item[property], term)) {
            return true;
          }
        } else if (
          item[property]
            .toString()
            .toLowerCase()
            .includes(toCompare)
        ) {
          return true;
        }
      }
      return false;
    }

    return items.filter(function (item) {
      return checkInside(item, term);
    });
  }
}
```

**Comment by prashantpimpale93** [comment]
@aVolpe Seems [this](https://stackoverflow.com/questions/58473489/library-build-fails-with-angular-9) is relevant to the current issue, please check and suggest, if okay then will do the changes in few day's.

**Comment by chris19960730** [comment]
> @chris19960730 Create a pipe in your project using
> 
> ```
> ng generate pipe CustomFilterPipe 
> ```
> 
> and just replace it with below code:
> 
> ```
> import { Pipe, PipeTransform, Injectable } from "@angular/core";
> 
> @Pipe({
>   name: "filter",
>   pure: false
> })
> @Injectable()
> export class CustomFilterPipe implements PipeTransform {
> 
>   transform(items: any, term: string, excludes: any = []): any {
>     if (!term || !items) return items;
>     return Custom_Ng2SearchPipe.filter(items, term, excludes);
>   }
> 
>   static filter(
>     items: Array<{ [key: string]: any }>,
>     term: string,
>     excludes: any
>   ): Array<{ [key: string]: any }> {
>     const toCompare = term.toLowerCase();
> 
>     function checkInside(item: any, term: string) {
>       if (
>         typeof item === "string" &&
>         item
>           .toString()
>           .toLowerCase()
>           .includes(toCompare)
>       ) {
>         return true;
>       }
> 
>       for (let property in item) {
>         if (
>           item[property] === null ||
>           item[property] == undefined ||
>           excludes.includes(property)
>         ) {
>           continue;
>         }
> 
>         if (typeof item[property] === "object") {
>           if (checkInside(item[property], term)) {
>             return true;
>           }
>         } else if (
>           item[property]
>             .toString()
>             .toLowerCase()
>             .includes(toCompare)
>         ) {
>           return true;
>         }
>       }
>       return false;
>     }
> 
>     return items.filter(function (item) {
>       return checkInside(item, term);
>     });
>   }
> }
> ```
> 
> Let us know if it works!
> 
> **I have tested it and working fine, check [this](https://stackblitz.com/edit/angular-yb5xd2) demo**

Hi, it works with me! Thanks a lot!
