### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by AlexMGN** [solodynamo/ng2-search-filter#61]
Hi !

When i try to use ng2-search-filter and after add in app.module.ts, i have this error :

![image](https://user-images.githubusercontent.com/25293823/84778864-df7a6980-afe3-11ea-9ae4-cd3ed9ebfde5.png)

Otherwise, i don't have any else error...

My Angular version : ^9.2.4
ng2-search-filter version : ^0.5.1

I don't know why because when i delete ng2-search-filter in app.module.ts, the error disapear (But search filter don't work)..

Any idea ? Thanks !

**Comment by eggy4prlnt** [comment]
same

**Comment by eggy4prlnt** [comment]
how to solve it?
