### ISSUE TITLE
Is there a way to filter an observable using async method on the ngFor? 

### ISSUE THREAD

**Issue by Gee63** [solodynamo/ng2-search-filter#8]
Is it possible to use this filter on an observable list object? I'm getting a 'Cannot read property 'toLowerCase' of undefined' error. I see there's a closed issue with the same error but no improvement after reading the responses. 

Here is my code:

**component.ts**

import {Component, OnInit} from '@angular/core';
import {AngularFireDatabase, FirebaseListObservable} from 'angularfire2/database';

@Component({
  selector: 'app-careers-component',
  templateUrl: './careers-component.component.html',
  styleUrls: ['./careers-component.component.css']
})
export class CareersComponentComponent implements OnInit  {

  public isMobile: boolean;
  vacancies:FirebaseListObservable<any>;

  constructor(db:AngularFireDatabase) {
    this.vacancies = db.list('/vacancies');
  }

  ngOnInit() {
  }

}

**component.html**

<div id="careers-container">
  careers-component works!

  <input type="text" [(ngModel)]="term">

      <div class="vacancy mobile" *ngFor="let vacancy of vacancies | async | filter:term">
      <div class="multiple-mobile-wrapper">
        <div class="multiple-mobile"></div>
        <div class="multiple-comile-content">
          <p>{{vacancy.description }}</p>
          <p>{{vacancy.positionTitle }}</p>
          <p>{{vacancy.team }}</p>
        </div>
      </div>
    </div>
     
  </div>

</div>

**Comment by solodynamo** [comment]
I just merged a PR by @arturoblack related to using different types in search filter. You may reinstall the package and give it another try.

**Comment by Gee63** [comment]
Works perfectly with the fix! thank you!
